### ISSUE TITLE
Not compatible with TF 2.0

### ISSUE THREAD

**Issue by nicanor5** [bedapudi6788/deeppunct#8]
Hello,

I just wanted to tell you that this module is no longer working with the version 2.0 of TensorFlow.

I am getting the following error when importing:

AttributeError: module 'tensorflow' has no attribute 'set_random_seed'

The full traceback:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE with Anaconda plugin.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/ziotag_metis_env/lib/python3.7/site-packages/deepcorrect/__init__.py", line 1, in <module>
    from .deepcorrect import DeepCorrect
  File "/Applications/PyCharm CE with Anaconda plugin.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/ziotag_metis_env/lib/python3.7/site-packages/deepcorrect/deepcorrect.py", line 1, in <module>
    from txt2txt import build_model, infer
  File "/Applications/PyCharm CE with Anaconda plugin.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/ziotag_metis_env/lib/python3.7/site-packages/txt2txt/__init__.py", line 3, in <module>
    from .txt2txt import *
  File "/Applications/PyCharm CE with Anaconda plugin.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/anaconda3/envs/ziotag_metis_env/lib/python3.7/site-packages/txt2txt/txt2txt.py", line 8, in <module>
    tf.set_random_seed(6788)
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'
```

**Comment by bedapudi6788** [comment]
@nicanor5 thanks for letting me know. I updated the https://github.com/bedapudi6788/txt2txt/ library to fix this.
Since deepcorrect depends on a previous version of txt2txt, unfortunately, it won't be possible to update this repo.

**Comment by nicanor5** [comment]
Could you also take a look at the version dependencies of deepsegment please? They are even older and already not available in PiPy

**Comment by bedapudi6788** [comment]
@nicanor5 which python version are you using? unless you are using python >=3.7, all the dependencies should be available correctly.

**Comment by bedapudi6788** [comment]
@nicanor5 i updated the libraries and now they work correctly with latest tf and keras.

**Comment by nicanor5** [comment]
Hi @bedapudi6788, what branch are the updates for deepcorrect in? Master still is not compatible with TF 2.0

**Comment by bedapudi6788** [comment]
@nicanor5 I meant, I update the txt2txt package and seqtag-keras, deepsegment. Updating the deepcorrect package isn't possible as it is dependent on an older version of txt2txt.
